### PR TITLE
Fix import wallet account instead of creating account? #111

### LINKED ISSUE #111: how to import wallet account instead of creating account?

### PR DESCRIPTION
**Pull request by dnKaratzas**
It would be nice to be able to import a wallet account! Fixes #111 
We don't want to edit the package to add that functionality locally

### CODE REVIEW

File: web3swift/src/Account/EthereumAccount.swift [hunk 1]
```diff
@@ -76,6 +76,19 @@ public class EthereumAccount: EthereumAccountProtocol {
             throw EthereumAccountError.createAccountError
         }
     }
+
+	public static func importAccount(keyStorage: EthereumKeyStorageProtocol, privateKey: String, keystorePassword password: String) throws -> EthereumAccount {
```
Comment (DarthMike) [inline web3swift/src/Account/EthereumAccount.swift:80]: Can you change `privateKey` to be `Data`, then you'll avoid the throw below.

**Comment by DarthMike** [comment]
Great thanks for the PR, see the comment above, plus could you please add a unit test for this new method?

File: web3swift/src/Account/EthereumAccount.swift (hunk 1 above)
Comment (dnKaratzas) [reply web3swift/src/Account/EthereumAccount.swift:80]: You are right!

**Comment by dnKaratzas** [comment]
> Great thanks for the PR, see the comment above, plus could you please add a unit test for this new method?

Added the unit test. About changing the privateKey as Data I dont agree with that. Its better to create an overloaded method to accept also Data as param instead of accepting only Data.

File: web3sTests/Account/EthereumAccountTests.swift [hunk 2]
```diff
@@ -28,6 +28,12 @@ class EthereumAccountTests: XCTestCase {
         let account = try? EthereumAccount.create(keyStorage: EthereumKeyLocalStorage(), keystorePassword: "PASSWORD")
         XCTAssertNotNil(account, "Failed to create account. Ensure key is valid in TestConfig.swift")
     }
+
+	func testImportAccount() {
+		let account = try? EthereumAccount.importAccount(keyStorage: EthereumKeyLocalStorage(), privateKey: "0x2639f727ded571d584643895d43d02a7a190f8249748a2c32200cfc12dde7173", keystorePassword: "PASSWORD")
+
+		XCTAssertNotNil(account, "Failed to import account.")
```
Comment (DarthMike) [inline web3sTests/Account/EthereumAccountTests.swift:35]: Sorry for nitpick, but better to check account?.address.value == "0x..." instead of nil to be sure it was imported correctly

Comment (dnKaratzas) [reply web3sTests/Account/EthereumAccountTests.swift:35]: Ok perfect ;)

File: web3swift/src/Account/EthereumAccount.swift (hunk 1 above)
Comment (DarthMike) [reply web3swift/src/Account/EthereumAccount.swift:81]: Sure, can be either way
