### PR TITLE
[CHANGE] Remove workaround returning '0x' when eth_call fails

### LINKED ISSUE #120: Remove logic around 'execution error' calls
See #118 and #119 

We included some logic to keep library working as before, but geth nodes are expected to be updated, this logic is obsolete.

Remove the workaround and just fail, giving the proper error to the caller.

### PR DESCRIPTION
**Pull request by DarthMike**
Fixes #120 

Also addressing the changes suggested in #183 @dnKaratzas

### CODE REVIEW

File: web3sTests/Client/EthereumClientTests.swift [hunk 1]
```diff
@@ -325,32 +323,20 @@ extension EthereumClientTests {
...
 
-    // This is how geth used to work up until a recent version
-    // see https://github.com/ethereum/go-ethereum/pull/21083/
-    // Used to return '0x' in response, and would fail decoding
-    // We'll continue to support this as user of library (and Argent in our case)
-    // works with this assumption.
-    // NOTE: This behaviour will be removed at a later time to fail as expected
-    // NOTE: At the time of writing, this test succeeds as-is in ropsten as nodes behaviour is different. That's why we use a mainnet check here
-    func test_GivenUnimplementedMethod_WhenCallingContract_ThenFailsWith0x_Async() async {
+    func test_GivenUnimplementedMethod_WhenCallingContract_ThenFailsWithExecutionError_Async() async {
```
Comment (DarthMike) [inline web3sTests/Client/EthereumClientTests.swift:326]: Change in default behaviour

File: web3swift/src/Client/EthereumClient.swift [hunk 2]
```diff
@@ -80,7 +80,7 @@ public protocol EthereumClientProtocol {
 
 public enum EthereumClientError: Error, Equatable {
     case tooManyResults
-    case executionError(description: String)
+    case executionError(JSONRPCErrorDetail)
```
Comment (DarthMike) [inline web3swift/src/Client/EthereumClient.swift:83]: The error now passed to caller to inspect if needed

File: web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift [hunk 3]
```diff
@@ -26,22 +26,41 @@ public extension ABIFunction {
 
     }
 
-    func call<T: ABIResponse>(withClient client: EthereumClientProtocol, responseType: T.Type, block: EthereumBlock = .Latest, completion: @escaping((EthereumClientError?, T?) -> Void)) {
+    func call<T: ABIResponse>(
+        withClient client: EthereumClientProtocol,
+        responseType: T.Type,
+        block: EthereumBlock = .Latest,
+        failOnExecutionError: Bool = true,
```
Comment (DarthMike) [inline web3swift/src/Contract/Statically Typed/EthereumClient+Static.swift:33]: Caller an still use previous behaviour (i.e. don't care if method exists, just default to 0/0x if it doesn't) for simplified logic

**Review by mluisbrown — APPROVED** [review]

File: web3swift/src/Client/JSONRPC.swift [hunk 4]
```diff
@@ -25,9 +25,21 @@ public struct JSONRPCResult<T: Decodable>: Decodable {
     var result: T
 }
 
-public struct JSONRPCErrorDetail: Decodable {
+public struct JSONRPCErrorDetail: Decodable, Equatable, CustomStringConvertible {
     var code: Int
```
Comment (dmcrodrigues) [inline web3swift/src/Client/JSONRPC.swift:29]: `code` and `message` should be public as well to provide more flexibility to consumers since we're now exposing it.

**Review by dmcrodrigues — APPROVED** [review]

File: web3swift/src/Client/JSONRPC.swift (hunk 4 above)
Comment (DarthMike) [reply web3swift/src/Client/JSONRPC.swift:29]: 👍

**Comment by dnKaratzas** [comment]
That PR resolves also #204

**Comment by dnKaratzas** [comment]
That PR solves #204
